services:
  rabbitmq-service:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"   # the port RabbitMQ will listen on
      - "8080:15672"  # the port the dashboard web service will be available from
